export type ToolCategory = 'pdf' | 'images' | 'writing' | 'detection' | 'conversion' | 'devtools' | 'utilities'

export interface Tool {
  id: string
  slug: string
  name: string
  description: string
  category: ToolCategory
  icon: string
  tags: string[]
  isAI: boolean
  isFree: boolean
  metaTitle: string
  metaDescription: string
}

export const CATEGORIES: Record<ToolCategory, { label: string; description: string; icon: string; color: string }> = {
  pdf: {
    label: 'PDF & Documents',
    description: 'Fusionnez, découpez, convertissez vos fichiers PDF',
    icon: '📄',
    color: 'from-red-500/20 to-orange-500/20',
  },
  images: {
    label: 'Images',
    description: 'Compressez, convertissez, éditez vos images',
    icon: '🖼️',
    color: 'from-blue-500/20 to-cyan-500/20',
  },
  writing: {
    label: 'Écriture IA',
    description: 'Rédigez, reformulez, améliorez vos textes avec l\'IA',
    icon: '✍️',
    color: 'from-purple-500/20 to-pink-500/20',
  },
  detection: {
    label: 'Détection & IA',
    description: 'Analysez et humanisez les textes générés par IA',
    icon: '🤖',
    color: 'from-green-500/20 to-teal-500/20',
  },
  conversion: {
    label: 'Conversion Fichiers',
    description: 'Convertissez CSV, JSON, Excel et autres formats',
    icon: '🔄',
    color: 'from-yellow-500/20 to-amber-500/20',
  },
  devtools: {
    label: 'Dev Tools',
    description: 'Outils pour développeurs : SQL, JSON, HTML, regex',
    icon: '💻',
    color: 'from-indigo-500/20 to-blue-500/20',
  },
  utilities: {
    label: 'Utilitaires',
    description: 'Calculateurs, générateurs et outils pratiques',
    icon: '🔢',
    color: 'from-slate-500/20 to-gray-500/20',
  },
}

export const TOOLS: Tool[] = [
  // PDF & Documents (8)
  {
    id: 'pdf-merge',
    slug: 'fusion-pdf',
    name: 'Fusion PDF',
    description: 'Combinez plusieurs fichiers PDF en un seul document',
    category: 'pdf',
    icon: '🔗',
    tags: ['pdf', 'fusion', 'merge', 'combiner'],
    isAI: false,
    isFree: true,
    metaTitle: 'Fusionner PDF en ligne gratuitement | Zouti',
    metaDescription: 'Combinez plusieurs fichiers PDF en un seul. Outil gratuit, sans inscription, 100% en ligne.',
  },
  {
    id: 'pdf-split',
    slug: 'decouper-pdf',
    name: 'Découper PDF',
    description: 'Extrayez des pages spécifiques de votre PDF',
    category: 'pdf',
    icon: '✂️',
    tags: ['pdf', 'split', 'découper', 'pages'],
    isAI: false,
    isFree: true,
    metaTitle: 'Découper un PDF en ligne gratuitement | Zouti',
    metaDescription: 'Extrayez des pages de votre PDF facilement. Outil gratuit, sans inscription.',
  },
  {
    id: 'pdf-rotate',
    slug: 'rotation-pdf',
    name: 'Rotation & Pages PDF',
    description: 'Réorganisez et faites pivoter les pages de votre PDF',
    category: 'pdf',
    icon: '🔄',
    tags: ['pdf', 'rotation', 'pages', 'réorganiser'],
    isAI: false,
    isFree: true,
    metaTitle: 'Rotation de pages PDF en ligne | Zouti',
    metaDescription: 'Faites pivoter ou réorganisez les pages de votre PDF. Gratuit et sans inscription.',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-en-pdf',
    name: 'Images → PDF',
    description: 'Convertissez des images JPG/PNG en fichier PDF',
    category: 'pdf',
    icon: '🖼️',
    tags: ['pdf', 'images', 'convertir', 'jpg', 'png'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir images en PDF en ligne | Zouti',
    metaDescription: 'Transformez vos images JPG et PNG en PDF. Outil gratuit en ligne.',
  },
  {
    id: 'pdf-to-images',
    slug: 'pdf-en-images',
    name: 'PDF → Images',
    description: 'Convertissez chaque page PDF en image JPG/PNG',
    category: 'pdf',
    icon: '📸',
    tags: ['pdf', 'images', 'convertir', 'jpg', 'png'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir PDF en images en ligne | Zouti',
    metaDescription: 'Extrayez chaque page de votre PDF en image. Gratuit et sans logiciel.',
  },
  {
    id: 'pdf-watermark',
    slug: 'filigrane-pdf',
    name: 'Filigrane PDF',
    description: 'Ajoutez un filigrane texte ou image à votre PDF',
    category: 'pdf',
    icon: '💧',
    tags: ['pdf', 'filigrane', 'watermark', 'protection'],
    isAI: false,
    isFree: true,
    metaTitle: 'Ajouter un filigrane à un PDF | Zouti',
    metaDescription: 'Ajoutez facilement un filigrane à vos PDF. Gratuit en ligne.',
  },
  {
    id: 'pdf-extract-text',
    slug: 'extraire-texte-pdf',
    name: 'Extraire texte PDF',
    description: 'Extrayez tout le texte d\'un PDF en format brut',
    category: 'pdf',
    icon: '📝',
    tags: ['pdf', 'texte', 'extraire', 'copier'],
    isAI: false,
    isFree: true,
    metaTitle: 'Extraire le texte d\'un PDF | Zouti',
    metaDescription: 'Copiez le contenu texte de n\'importe quel PDF. Gratuit et instantané.',
  },
  {
    id: 'pdf-summarize',
    slug: 'resumer-pdf',
    name: 'Résumeur de PDF (IA)',
    description: 'Obtenez un résumé intelligent de votre PDF en secondes',
    category: 'pdf',
    icon: '🧠',
    tags: ['pdf', 'résumé', 'ia', 'analyse', 'intelligence artificielle'],
    isAI: true,
    isFree: true,
    metaTitle: 'Résumer un PDF avec l\'IA | Zouti',
    metaDescription: 'Résumé automatique de vos PDF par intelligence artificielle. Gratuit en ligne.',
  },

  // Images (8)
  {
    id: 'image-compress',
    slug: 'comprimer-image',
    name: 'Compresser Image',
    description: 'Réduisez le poids de vos images sans perte visible',
    category: 'images',
    icon: '📦',
    tags: ['image', 'compression', 'jpg', 'png', 'webp'],
    isAI: false,
    isFree: true,
    metaTitle: 'Compresser une image en ligne | Zouti',
    metaDescription: 'Réduisez la taille de vos images JPG, PNG, WebP gratuitement en ligne.',
  },
  {
    id: 'image-convert',
    slug: 'convertir-image',
    name: 'Convertir Format Image',
    description: 'Convertissez entre JPG, PNG, WebP et autres formats',
    category: 'images',
    icon: '🔄',
    tags: ['image', 'convertir', 'jpg', 'png', 'webp', 'format'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir format image en ligne | Zouti',
    metaDescription: 'Convertissez JPG en PNG, WebP, AVIF et vice versa. Gratuit en ligne.',
  },
  {
    id: 'image-resize',
    slug: 'redimensionner-image',
    name: 'Redimensionner Image',
    description: 'Modifiez la taille de vos images en pixels ou pourcentage',
    category: 'images',
    icon: '📐',
    tags: ['image', 'resize', 'redimensionner', 'taille'],
    isAI: false,
    isFree: true,
    metaTitle: 'Redimensionner une image en ligne | Zouti',
    metaDescription: 'Changez la taille de vos images facilement. Gratuit et sans inscription.',
  },
  {
    id: 'image-crop',
    slug: 'recadrer-image',
    name: 'Recadrage Intelligent',
    description: 'Recadrez vos images en détectant automatiquement le sujet',
    category: 'images',
    icon: '✂️',
    tags: ['image', 'recadrer', 'crop', 'rogner'],
    isAI: false,
    isFree: true,
    metaTitle: 'Recadrer une image en ligne | Zouti',
    metaDescription: 'Recadrage intelligent de vos images avec détection du sujet. Gratuit.',
  },
  {
    id: 'image-bg-remove',
    slug: 'supprimer-fond-image',
    name: 'Supprimer le fond (IA)',
    description: 'Supprimez automatiquement l\'arrière-plan de vos images',
    category: 'images',
    icon: '🪄',
    tags: ['image', 'fond', 'background', 'remove', 'ia', 'transparent'],
    isAI: true,
    isFree: true,
    metaTitle: 'Supprimer le fond d\'une image | Zouti',
    metaDescription: 'Effacez l\'arrière-plan de vos photos automatiquement avec l\'IA. 100% gratuit.',
  },
  {
    id: 'image-ocr',
    slug: 'extraire-texte-image',
    name: 'Extraire texte d\'image (OCR)',
    description: 'Convertissez le texte présent dans une image en texte éditable',
    category: 'images',
    icon: '🔍',
    tags: ['ocr', 'image', 'texte', 'extraire', 'reconnaissance'],
    isAI: false,
    isFree: true,
    metaTitle: 'OCR - Extraire texte d\'une image | Zouti',
    metaDescription: 'Reconnaissance optique de caractères (OCR) pour extraire le texte de vos images.',
  },
  {
    id: 'qrcode',
    slug: 'generateur-qr-code',
    name: 'Générateur QR Code',
    description: 'Créez des QR codes personnalisés avec couleurs et logo',
    category: 'images',
    icon: '📱',
    tags: ['qrcode', 'qr', 'code', 'générateur', 'url'],
    isAI: false,
    isFree: true,
    metaTitle: 'Générateur QR Code gratuit | Zouti',
    metaDescription: 'Créez des QR codes personnalisés gratuitement. Téléchargement PNG immédiat.',
  },
  {
    id: 'thumbnail',
    slug: 'miniature-youtube',
    name: 'Miniature YouTube',
    description: 'Créez des miniatures YouTube au format optimisé 1280×720',
    category: 'images',
    icon: '▶️',
    tags: ['youtube', 'miniature', 'thumbnail', 'vidéo'],
    isAI: false,
    isFree: true,
    metaTitle: 'Créateur de miniature YouTube | Zouti',
    metaDescription: 'Créez des miniatures YouTube 1280x720 optimisées. Outil gratuit en ligne.',
  },

  // Writing AI (13)
  {
    id: 'write-article',
    slug: 'redacteur-article',
    name: 'Rédacteur d\'articles',
    description: 'Générez des articles complets et optimisés SEO',
    category: 'writing',
    icon: '📰',
    tags: ['article', 'rédaction', 'seo', 'ia', 'blog'],
    isAI: true,
    isFree: true,
    metaTitle: 'Rédiger un article avec l\'IA | Zouti',
    metaDescription: 'Générez des articles de blog optimisés SEO avec l\'intelligence artificielle.',
  },
  {
    id: 'write-rephrase',
    slug: 'reformulateur',
    name: 'Reformulateur',
    description: 'Reformulez n\'importe quel texte en conservant le sens',
    category: 'writing',
    icon: '🔀',
    tags: ['reformuler', 'paraphrase', 'réécrire', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Reformuler un texte avec l\'IA | Zouti',
    metaDescription: 'Reformulez et paraphrasez n\'importe quel texte gratuitement avec l\'IA.',
  },
  {
    id: 'write-correct',
    slug: 'correcteur-texte',
    name: 'Correcteur orthographique',
    description: 'Corrigez orthographe, grammaire et style en un clic',
    category: 'writing',
    icon: '✅',
    tags: ['correction', 'orthographe', 'grammaire', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Correcteur orthographique IA en ligne | Zouti',
    metaDescription: 'Corrigez vos textes automatiquement avec l\'intelligence artificielle.',
  },
  {
    id: 'write-improve',
    slug: 'ameliorateur-texte',
    name: 'Améliorateur de texte',
    description: 'Rendez vos textes plus fluides, percutants et professionnels',
    category: 'writing',
    icon: '⬆️',
    tags: ['améliorer', 'texte', 'qualité', 'ia', 'rédaction'],
    isAI: true,
    isFree: true,
    metaTitle: 'Améliorer un texte avec l\'IA | Zouti',
    metaDescription: 'Améliorez la qualité de vos textes instantanément avec l\'intelligence artificielle.',
  },
  {
    id: 'write-summarize',
    slug: 'resumeur-texte',
    name: 'Résumeur de texte',
    description: 'Condensez n\'importe quel texte en points clés',
    category: 'writing',
    icon: '📋',
    tags: ['résumé', 'résumer', 'condenser', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Résumer un texte automatiquement | Zouti',
    metaDescription: 'Résumez automatiquement n\'importe quel texte avec l\'IA. Gratuit.',
  },
  {
    id: 'write-expand',
    slug: 'developper-texte',
    name: 'Développeur de texte',
    description: 'Étendez et enrichissez un texte court en contenu complet',
    category: 'writing',
    icon: '📈',
    tags: ['développer', 'étoffer', 'allonger', 'ia', 'contenu'],
    isAI: true,
    isFree: true,
    metaTitle: 'Développer et étoffer un texte | Zouti',
    metaDescription: 'Transformez un texte court en contenu riche et détaillé avec l\'IA.',
  },
  {
    id: 'write-simplify',
    slug: 'simplificateur-texte',
    name: 'Simplificateur de texte',
    description: 'Rendez les textes complexes clairs et accessibles',
    category: 'writing',
    icon: '🔡',
    tags: ['simplifier', 'clarifier', 'accessibilité', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Simplifier un texte complexe | Zouti',
    metaDescription: 'Simplifiez les textes juridiques, techniques ou complexes avec l\'IA.',
  },
  {
    id: 'write-email',
    slug: 'generateur-email',
    name: 'Générateur d\'emails pro',
    description: 'Rédigez des emails professionnels adaptés à chaque situation',
    category: 'writing',
    icon: '📧',
    tags: ['email', 'mail', 'professionnel', 'ia', 'rédiger'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur d\'email professionnel | Zouti',
    metaDescription: 'Rédigez des emails professionnels avec l\'IA. Adapté à toutes les situations.',
  },
  {
    id: 'write-social',
    slug: 'generateur-posts-sociaux',
    name: 'Générateur posts réseaux sociaux',
    description: 'Créez des posts LinkedIn, Instagram, X engageants',
    category: 'writing',
    icon: '📲',
    tags: ['social', 'linkedin', 'instagram', 'post', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur de posts réseaux sociaux | Zouti',
    metaDescription: 'Créez des posts LinkedIn, Instagram, X avec l\'IA. Gratuit en ligne.',
  },
  {
    id: 'write-letter',
    slug: 'generateur-lettre',
    name: 'Générateur de lettres',
    description: 'Rédigez des lettres formelles, administratives ou commerciales',
    category: 'writing',
    icon: '📬',
    tags: ['lettre', 'courrier', 'formel', 'administratif', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur de lettre formelle | Zouti',
    metaDescription: 'Rédigez des lettres professionnelles et administratives avec l\'IA.',
  },
  {
    id: 'write-product',
    slug: 'description-produit',
    name: 'Description produit e-commerce',
    description: 'Générez des descriptions produits optimisées pour vendre',
    category: 'writing',
    icon: '🛍️',
    tags: ['produit', 'e-commerce', 'description', 'ia', 'vente'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur description produit e-commerce | Zouti',
    metaDescription: 'Générez des descriptions produits qui convertissent avec l\'IA.',
  },
  {
    id: 'write-keywords',
    slug: 'extracteur-mots-cles',
    name: 'Extracteur de mots-clés SEO',
    description: 'Extrayez les mots-clés principaux d\'un texte pour le SEO',
    category: 'writing',
    icon: '🔑',
    tags: ['seo', 'mots-clés', 'keywords', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Extracteur de mots-clés SEO | Zouti',
    metaDescription: 'Identifiez les mots-clés importants de vos textes pour le référencement.',
  },
  {
    id: 'write-tone',
    slug: 'changeur-de-ton',
    name: 'Changeur de ton',
    description: 'Adaptez le registre de votre texte : formel, casual, persuasif',
    category: 'writing',
    icon: '🎭',
    tags: ['ton', 'registre', 'formel', 'casual', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Changer le ton d\'un texte | Zouti',
    metaDescription: 'Adaptez le registre de n\'importe quel texte avec l\'IA. Formel, casual ou persuasif.',
  },

  // Detection (4)
  {
    id: 'ai-humanize',
    slug: 'humaniser-texte-ia',
    name: 'Humaniseur de texte IA',
    description: 'Transformez un texte généré par IA en écriture naturelle',
    category: 'detection',
    icon: '🧬',
    tags: ['humaniser', 'ia', 'naturel', 'détection', 'chatgpt'],
    isAI: true,
    isFree: true,
    metaTitle: 'Humaniser un texte généré par IA | Zouti',
    metaDescription: 'Rendez votre texte IA indétectable et plus naturel. Gratuit en ligne.',
  },
  {
    id: 'ai-tone-analyze',
    slug: 'analyseur-de-ton',
    name: 'Analyseur de ton',
    description: 'Détectez le registre et l\'intention d\'un texte',
    category: 'detection',
    icon: '🎯',
    tags: ['ton', 'analyse', 'registre', 'sentiment', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Analyser le ton d\'un texte | Zouti',
    metaDescription: 'Analysez le registre et l\'intention d\'un texte avec l\'IA.',
  },
  {
    id: 'text-diff',
    slug: 'comparateur-textes',
    name: 'Comparateur de versions',
    description: 'Comparez deux textes et visualisez les différences',
    category: 'detection',
    icon: '⚖️',
    tags: ['comparer', 'diff', 'versions', 'différences'],
    isAI: false,
    isFree: true,
    metaTitle: 'Comparer deux textes en ligne | Zouti',
    metaDescription: 'Visualisez les différences entre deux versions de texte. Gratuit.',
  },
  {
    id: 'readability',
    slug: 'analyseur-lisibilite',
    name: 'Analyseur de lisibilité',
    description: 'Calculez le score de lisibilité Flesch de votre texte',
    category: 'detection',
    icon: '📊',
    tags: ['lisibilité', 'flesch', 'score', 'analyse', 'clarté'],
    isAI: false,
    isFree: true,
    metaTitle: 'Analyser la lisibilité d\'un texte | Zouti',
    metaDescription: 'Calculez le score de lisibilité de vos textes (indice Flesch). Gratuit.',
  },

  // Conversion (11)
  {
    id: 'csv-to-json',
    slug: 'csv-en-json',
    name: 'CSV → JSON',
    description: 'Convertissez vos fichiers CSV en format JSON',
    category: 'conversion',
    icon: '🔄',
    tags: ['csv', 'json', 'convertir', 'données'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir CSV en JSON en ligne | Zouti',
    metaDescription: 'Convertissez vos fichiers CSV en JSON instantanément. Gratuit en ligne.',
  },
  {
    id: 'json-to-csv',
    slug: 'json-en-csv',
    name: 'JSON → CSV',
    description: 'Transformez vos données JSON en fichier CSV',
    category: 'conversion',
    icon: '🔄',
    tags: ['json', 'csv', 'convertir', 'données'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir JSON en CSV en ligne | Zouti',
    metaDescription: 'Transformez votre JSON en CSV facilement. Outil gratuit en ligne.',
  },
  {
    id: 'excel-to-csv',
    slug: 'excel-en-csv',
    name: 'Excel → CSV',
    description: 'Exportez vos feuilles Excel en format CSV',
    category: 'conversion',
    icon: '📊',
    tags: ['excel', 'csv', 'xlsx', 'convertir'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir Excel en CSV en ligne | Zouti',
    metaDescription: 'Exportez vos fichiers Excel en CSV. Gratuit et sans logiciel.',
  },
  {
    id: 'csv-to-excel',
    slug: 'csv-en-excel',
    name: 'CSV → Excel',
    description: 'Convertissez vos CSV en fichier Excel formaté',
    category: 'conversion',
    icon: '📗',
    tags: ['csv', 'excel', 'xlsx', 'convertir'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir CSV en Excel en ligne | Zouti',
    metaDescription: 'Transformez vos fichiers CSV en Excel. Gratuit et instantané.',
  },
  {
    id: 'xml-to-json',
    slug: 'xml-en-json',
    name: 'XML → JSON',
    description: 'Parsez et convertissez vos fichiers XML en JSON',
    category: 'conversion',
    icon: '🔀',
    tags: ['xml', 'json', 'convertir', 'parser'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir XML en JSON en ligne | Zouti',
    metaDescription: 'Convertissez vos fichiers XML en JSON. Outil gratuit en ligne.',
  },
  {
    id: 'md-to-html',
    slug: 'markdown-en-html',
    name: 'Markdown → HTML',
    description: 'Convertissez votre Markdown en code HTML',
    category: 'conversion',
    icon: '📝',
    tags: ['markdown', 'html', 'convertir', 'md'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir Markdown en HTML | Zouti',
    metaDescription: 'Transformez votre Markdown en HTML propre. Gratuit en ligne.',
  },
  {
    id: 'html-to-md',
    slug: 'html-en-markdown',
    name: 'HTML → Markdown',
    description: 'Convertissez du HTML en syntaxe Markdown',
    category: 'conversion',
    icon: '📄',
    tags: ['html', 'markdown', 'convertir', 'md'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir HTML en Markdown | Zouti',
    metaDescription: 'Transformez votre HTML en Markdown. Gratuit et instantané.',
  },
  {
    id: 'txt-to-pdf',
    slug: 'txt-en-pdf',
    name: 'TXT → PDF',
    description: 'Créez un PDF formaté à partir de votre texte brut',
    category: 'conversion',
    icon: '📋',
    tags: ['txt', 'pdf', 'convertir', 'texte'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir TXT en PDF en ligne | Zouti',
    metaDescription: 'Créez un PDF à partir de texte brut. Gratuit et instantané.',
  },
  {
    id: 'zip-extract',
    slug: 'extraire-zip',
    name: 'Extraction ZIP',
    description: 'Extrayez et visualisez le contenu d\'une archive ZIP',
    category: 'conversion',
    icon: '📦',
    tags: ['zip', 'extraire', 'archive', 'décompresser'],
    isAI: false,
    isFree: true,
    metaTitle: 'Extraire un fichier ZIP en ligne | Zouti',
    metaDescription: 'Décompressez vos archives ZIP directement dans le navigateur.',
  },
  {
    id: 'base64',
    slug: 'encodeur-base64',
    name: 'Encodeur/Décodeur Base64',
    description: 'Encodez et décodez du texte et des images en Base64',
    category: 'conversion',
    icon: '🔐',
    tags: ['base64', 'encodeur', 'décodeur', 'encode'],
    isAI: false,
    isFree: true,
    metaTitle: 'Encodeur Décodeur Base64 en ligne | Zouti',
    metaDescription: 'Encodez et décodez en Base64 facilement. Outil gratuit en ligne.',
  },
  {
    id: 'url-encode',
    slug: 'encodeur-url',
    name: 'Encodeur/Décodeur URL',
    description: 'Encodez et décodez les paramètres d\'URL',
    category: 'conversion',
    icon: '🌐',
    tags: ['url', 'encode', 'decode', 'paramètres'],
    isAI: false,
    isFree: true,
    metaTitle: 'Encodeur Décodeur URL en ligne | Zouti',
    metaDescription: 'Encodez et décodez des URLs. Outil gratuit en ligne.',
  },

  // Dev Tools (13)
  {
    id: 'html-preview',
    slug: 'visualiseur-html',
    name: 'Visualiseur HTML live',
    description: 'Prévisualisez votre code HTML en temps réel',
    category: 'devtools',
    icon: '👁️',
    tags: ['html', 'preview', 'visualiser', 'live', 'dev'],
    isAI: false,
    isFree: true,
    metaTitle: 'Visualiseur HTML live en ligne | Zouti',
    metaDescription: 'Prévisualisez votre HTML en temps réel. Éditeur en ligne gratuit.',
  },
  {
    id: 'html-editor',
    slug: 'editeur-html-css-js',
    name: 'Éditeur HTML/CSS/JS',
    description: 'Éditeur de code avec preview HTML, CSS et JavaScript',
    category: 'devtools',
    icon: '💻',
    tags: ['html', 'css', 'javascript', 'éditeur', 'dev'],
    isAI: false,
    isFree: true,
    metaTitle: 'Éditeur HTML CSS JS en ligne | Zouti',
    metaDescription: 'Codez HTML, CSS, JavaScript avec preview en temps réel. Gratuit.',
  },
  {
    id: 'json-format',
    slug: 'formateur-json',
    name: 'JSON Formatter & Validator',
    description: 'Formatez, validez et colorez votre JSON',
    category: 'devtools',
    icon: '📋',
    tags: ['json', 'formatter', 'validator', 'beautify', 'dev'],
    isAI: false,
    isFree: true,
    metaTitle: 'Formater et valider du JSON en ligne | Zouti',
    metaDescription: 'Beautifiez et validez votre JSON instantanément. Outil gratuit.',
  },
  {
    id: 'json-download',
    slug: 'telecharger-json',
    name: 'JSON → Fichier',
    description: 'Collez votre JSON et téléchargez-le en fichier .json',
    category: 'devtools',
    icon: '💾',
    tags: ['json', 'télécharger', 'fichier', 'export'],
    isAI: false,
    isFree: true,
    metaTitle: 'Télécharger du JSON en fichier | Zouti',
    metaDescription: 'Exportez votre JSON en fichier .json. Gratuit et instantané.',
  },
  {
    id: 'sql-gen',
    slug: 'generateur-sql',
    name: 'Générateur SQL (IA)',
    description: 'Décrivez votre requête en français, obtenez le SQL',
    category: 'devtools',
    icon: '🗄️',
    tags: ['sql', 'ia', 'requête', 'base de données', 'générer'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur SQL avec l\'IA | Zouti',
    metaDescription: 'Générez des requêtes SQL en décrivant votre besoin en français.',
  },
  {
    id: 'sql-format',
    slug: 'formateur-sql',
    name: 'Formateur SQL',
    description: 'Formatez et indentez proprement vos requêtes SQL',
    category: 'devtools',
    icon: '✨',
    tags: ['sql', 'formatter', 'beautify', 'indenter'],
    isAI: false,
    isFree: true,
    metaTitle: 'Formater du SQL en ligne | Zouti',
    metaDescription: 'Beautifiez et indentez vos requêtes SQL. Gratuit en ligne.',
  },
  {
    id: 'sql-run',
    slug: 'executeur-sql',
    name: 'Exécuteur SQL in-browser',
    description: 'Exécutez des requêtes SQL sur SQLite dans votre navigateur',
    category: 'devtools',
    icon: '▶️',
    tags: ['sql', 'sqlite', 'exécuter', 'query', 'base de données'],
    isAI: false,
    isFree: true,
    metaTitle: 'Exécuter du SQL en ligne | Zouti',
    metaDescription: 'Exécutez des requêtes SQL directement dans votre navigateur avec SQLite.',
  },
  {
    id: 'regex-builder',
    slug: 'regex-builder',
    name: 'Regex Builder (IA)',
    description: 'Décrivez votre pattern, l\'IA génère l\'expression régulière',
    category: 'devtools',
    icon: '🔎',
    tags: ['regex', 'expression régulière', 'ia', 'pattern'],
    isAI: true,
    isFree: true,
    metaTitle: 'Créer une Regex avec l\'IA | Zouti',
    metaDescription: 'Générez des expressions régulières en langage naturel avec l\'IA.',
  },
  {
    id: 'minifier',
    slug: 'minifier-beautifier',
    name: 'Minifier / Beautifier',
    description: 'Minifiez ou formatez HTML, CSS, JS, JSON',
    category: 'devtools',
    icon: '🗜️',
    tags: ['minifier', 'beautifier', 'html', 'css', 'js', 'json'],
    isAI: false,
    isFree: true,
    metaTitle: 'Minifier et Beautifier code en ligne | Zouti',
    metaDescription: 'Minifiez ou embellissez votre HTML, CSS, JavaScript, JSON.',
  },
  {
    id: 'jwt-decode',
    slug: 'decodeur-jwt',
    name: 'Décodeur JWT',
    description: 'Décodez et inspectez vos tokens JWT',
    category: 'devtools',
    icon: '🔑',
    tags: ['jwt', 'token', 'décoder', 'claims', 'authentification'],
    isAI: false,
    isFree: true,
    metaTitle: 'Décoder un token JWT en ligne | Zouti',
    metaDescription: 'Décodez et inspectez vos tokens JWT. Gratuit et instantané.',
  },
  {
    id: 'mock-json',
    slug: 'generateur-json-mock',
    name: 'Générateur JSON Mock',
    description: 'Générez des données JSON fictives pour vos tests',
    category: 'devtools',
    icon: '🎲',
    tags: ['json', 'mock', 'données', 'test', 'ia'],
    isAI: true,
    isFree: true,
    metaTitle: 'Générateur de données JSON Mock | Zouti',
    metaDescription: 'Générez des données JSON fictives pour vos tests et prototypes.',
  },
  {
    id: 'code-diff',
    slug: 'diff-code',
    name: 'Diff de code',
    description: 'Comparez deux versions de code côte à côte',
    category: 'devtools',
    icon: '📑',
    tags: ['diff', 'code', 'comparer', 'versions'],
    isAI: false,
    isFree: true,
    metaTitle: 'Comparateur de code en ligne | Zouti',
    metaDescription: 'Comparez deux versions de code et visualisez les différences.',
  },
  {
    id: 'css-converter',
    slug: 'convertisseur-css',
    name: 'Convertisseur CSS px/rem/em',
    description: 'Convertissez entre px, rem, em et variables CSS',
    category: 'devtools',
    icon: '🎨',
    tags: ['css', 'px', 'rem', 'em', 'convertir'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertir px rem em CSS en ligne | Zouti',
    metaDescription: 'Convertissez entre px, rem et em facilement. Calculateur CSS gratuit.',
  },

  // Utilities (8)
  {
    id: 'tva-calc',
    slug: 'calculateur-tva',
    name: 'Calculateur TVA France',
    description: 'Calculez HT/TTC avec tous les taux de TVA français',
    category: 'utilities',
    icon: '💰',
    tags: ['tva', 'calcul', 'ht', 'ttc', 'france', 'impôt'],
    isAI: false,
    isFree: true,
    metaTitle: 'Calculateur TVA France HT/TTC | Zouti',
    metaDescription: 'Calculez la TVA française HT vers TTC et inversement. Gratuit en ligne.',
  },
  {
    id: 'password-gen',
    slug: 'generateur-mot-de-passe',
    name: 'Générateur mot de passe',
    description: 'Créez des mots de passe forts et sécurisés',
    category: 'utilities',
    icon: '🔒',
    tags: ['mot de passe', 'password', 'sécurité', 'générateur'],
    isAI: false,
    isFree: true,
    metaTitle: 'Générateur de mot de passe sécurisé | Zouti',
    metaDescription: 'Générez des mots de passe forts et sécurisés. Gratuit en ligne.',
  },
  {
    id: 'word-count',
    slug: 'compteur-mots',
    name: 'Compteur de mots',
    description: 'Comptez mots, caractères, phrases et temps de lecture',
    category: 'utilities',
    icon: '📊',
    tags: ['mots', 'caractères', 'compteur', 'texte'],
    isAI: false,
    isFree: true,
    metaTitle: 'Compteur de mots et caractères en ligne | Zouti',
    metaDescription: 'Comptez mots, caractères et estimez le temps de lecture. Gratuit.',
  },
  {
    id: 'uuid-gen',
    slug: 'generateur-uuid',
    name: 'Générateur UUID',
    description: 'Générez des UUID v4 uniques pour vos projets',
    category: 'utilities',
    icon: '🎲',
    tags: ['uuid', 'guid', 'identifiant', 'unique', 'générateur'],
    isAI: false,
    isFree: true,
    metaTitle: 'Générateur UUID en ligne | Zouti',
    metaDescription: 'Générez des UUID v4 uniques instantanément. Gratuit.',
  },
  {
    id: 'lorem-ipsum',
    slug: 'generateur-lorem-ipsum',
    name: 'Générateur Lorem Ipsum',
    description: 'Générez du texte Lorem Ipsum pour vos maquettes',
    category: 'utilities',
    icon: '📝',
    tags: ['lorem ipsum', 'texte', 'maquette', 'placeholder'],
    isAI: false,
    isFree: true,
    metaTitle: 'Générateur Lorem Ipsum en ligne | Zouti',
    metaDescription: 'Générez du texte Lorem Ipsum pour vos maquettes. Gratuit.',
  },
  {
    id: 'unit-convert',
    slug: 'convertisseur-unites',
    name: 'Convertisseur d\'unités',
    description: 'Convertissez poids, longueur, surface, température',
    category: 'utilities',
    icon: '📏',
    tags: ['unités', 'convertir', 'poids', 'longueur', 'température'],
    isAI: false,
    isFree: true,
    metaTitle: 'Convertisseur d\'unités en ligne | Zouti',
    metaDescription: 'Convertissez toutes les unités de mesure. Gratuit en ligne.',
  },
  {
    id: 'date-calc',
    slug: 'calculateur-dates',
    name: 'Calculateur de dates',
    description: 'Calculez délais, jours ouvrés et différences entre dates',
    category: 'utilities',
    icon: '📅',
    tags: ['date', 'délai', 'jours', 'calcul', 'calendrier'],
    isAI: false,
    isFree: true,
    metaTitle: 'Calculateur de dates et délais | Zouti',
    metaDescription: 'Calculez des délais, jours ouvrés et différences de dates. Gratuit.',
  },
  {
    id: 'color-picker',
    slug: 'testeur-couleurs',
    name: 'Testeur de couleurs',
    description: 'Convertissez et testez les couleurs HEX, RGB, HSL',
    category: 'utilities',
    icon: '🎨',
    tags: ['couleur', 'hex', 'rgb', 'hsl', 'palette', 'design'],
    isAI: false,
    isFree: true,
    metaTitle: 'Testeur convertisseur couleurs HEX RGB HSL | Zouti',
    metaDescription: 'Convertissez et testez vos couleurs HEX, RGB, HSL. Gratuit en ligne.',
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter(t => t.category === category)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.includes(q))
  )
}
